### ISSUE TITLE
api endpoint for subscribe

### ISSUE THREAD

**Issue by nttq1sub** [sabuhish/fastapi-mqtt#71]
@sabuhish  I am trying to create a api endpoint that subscribe to mqtt topic and return data when have api call to that endpoint. How can I implement that? I just see in the example for the publish, not subscribe?
Are you plan to switch to use paho client instead of gmqtt?
And I face a problem that to use mqtt with renew jwt, then use it as credential to subscribe to mqtt broker, in your code I didn't see the implementation for that?
Thanks so much for your support? If anyone want to support on implement above issues, I hope that we can co-operate to do that in case of the author does not have so much time for it.

**Comment by sabuhish** [comment]
@luongngochoa hmm I think the publish endpoint would be meaningful because we want to publish some data by posting, but subscribing should be possible when the app itself starts to run it should listen to certain topics. Paho is not planned since it was not fully implemented asyncio. There is already discussion going on about subscribe on #59 you might join us there.
