### ISSUE TITLE
Deprecation Warning

### ISSUE THREAD

**Issue by ftapajos** [sabuhish/fastapi-mqtt#90]
FastAPI: 0.105.0
fastapi-mqtt 2.1.1

```
 /usr/local/lib/python3.11/site-packages/fastapi_mqtt/fastmqtt.py:235: DeprecationWarning: 
          on_event is deprecated, use lifespan event handlers instead.
  
          Read more about it in the
          [FastAPI docs for Lifespan Events](https://fastapi.tiangolo.com/advanced/events/).
          
    @app.on_event("shutdown")
```

**Comment by azogue** [comment]
Hi @ftapajos, you should use a `lifespan`, as indicated in the warning, and use the `await fast_mqtt.mqtt_startup()` and `await fast_mqtt.mqtt_shutdown()` methods, instead of the old `fast_mqtt.init_app(app)` method 👌

An example of that is already in one of the included examples (examples/ws_app/app.py) --> https://github.com/sabuhish/fastapi-mqtt/blob/d4da8acdf1d6fe06a646cb616582abe06ae16a54/examples/ws_app/app.py#L27-L35

Both methods are valid, but the lifespan is preferred 👍
